{% set name = "xtal2png" %}
{% set version = "0.9.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xtal2png-{{ version }}.tar.gz
  sha256: a4dabfb2f2883ff1fc49d667375391bfed777493dd638bb4bdc9c94b8c88fe83

build:
  number: 0
  entry_points:
    - xtal2png = xtal2png.core:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools-scm
    - python >=3.6
  run:
    - numpy
    - pillow
    - pymatgen
    - python >=3.6
    - importlib-metadata
    - plotly
    - python-kaleido
test:
  imports:
    - xtal2png
    - xtal2png.utils
  commands:
    - pip check
    - xtal2png --help
  requires:
    - pip

about:
  home: https://github.com/sparks-baird/xtal2png/
  summary: Encode and decode crystal structures via portable networks graphics (PNG) files.
  dev_url: https://github.com/sparks-baird/xtal2png/
  doc_url: https://xtal2png.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sgbaird
