{% set name = "xtal2png" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xtal2png-{{ version }}.tar.gz
  sha256: 2a876e8bb3754d76e0ec52576b003c5486374cc8e38aa54d1524d367843286b2

build:
  number: 1
  entry_points:
    - xtal2png = xtal2png.core:run
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - setuptools-scm
    - python {{ python_min }}
  run:
    - numpy
    - pillow
    - pymatgen
    - python >={{ python_min }}
    - importlib-metadata
    - plotly
    - python-kaleido
test:
  imports:
    - xtal2png
    - xtal2png.utils
  commands:
    - pip check
    - xtal2png --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sparks-baird/xtal2png/
  summary: Encode and decode crystal structures via portable networks graphics (PNG) files.
  dev_url: https://github.com/sparks-baird/xtal2png/
  doc_url: https://xtal2png.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sgbaird
